title: ReTiSAR
email: hannes.helmholz@chalmers.se
description: >- # this means to ignore newlines until "baseurl:"
  Real-Time Spherical Microphone Renderer for binaural reproduction in Python
baseurl: ""
url: "https://appliedacousticschalmers.github.io/ReTiSAR/"
github_username: HaHeho

# Build settings
markdown: kramdown
theme: jekyll-theme-midnight
plugins:
  - jekyll-feed

# GitHub Pages configuration settings
# https://help.github.com/en/github/working-with-github-pages/about-github-pages-and-jekyll
lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
